### ISSUE TITLE
what does it mean by ftol?

### ISSUE THREAD

**Issue by xushanthu-2014** [jbrea/CMAEvolutionStrategy.jl#11]
Does ftol means the loss function values is smaller than this value, or the cost function value does not change more than this value? Thanks!

**Comment by jbrea** [comment]
`ftol` means [the loss function values is smaller than this value](https://github.com/jbrea/CMAEvolutionStrategy.jl/blob/6c5544a357db5dfe23ccd663663fbd881f3dca1d/src/stop.jl#L33).

**Comment by xushanthu-2014** [comment]
Thanks!
