### ISSUE TITLE
`xbest` doesn't return best x value

### ISSUE THREAD

**Issue by simonp0420** [jbrea/CMAEvolutionStrategy.jl#3]
First, thank you for creating this exceptional optimizer.  I've used it for several difficult problems with very good results.

I am working on an optimization problem as a consultant for a company that will not let me disclose my code, so I'll have to describe the problem and hopefully provide enough clues to allow a fix.

I have noticed that in some cases the `xbest` function doesn't actually return the x-vector corresponding to the best solution.  I first noticed this when I used the value returned by `xbest` as the argument to the objective function and did not get the optimum value back.  I verified this by adding some code to my objective function that saves the best (least) function value and the corresponding x-vector.  `fbest` agrees with my saved function value, but `xbest` doesn't agree with my saved x-value.  As an example:

```
julia> import CMAEvolutionStrategy as CMA

julia> CMA.fbest(result)
-45.94346204785836

julia> BO2.savebest.fbest
-45.94346204785836
```
so `fbest` agrees perfectly with my saved value, but

```
julia> CMA.xbest(result)
5-element Vector{Float64}:
 0.42283097791722574
 0.3041691378656208
 1.6913225029723962
 0.7950720935226006
 0.14124929162038333

julia> BO2.savebest.xbest
5-element Vector{Float64}:
 0.37081623974052036
 0.30097744387178793
 1.7031558962386453
 0.7901800056374355
 0.17100844173903773
```
When I plug my saved x-value back into the objective function, it of course returns the expected `fbest` value.

I realize this isn't the strongest evidence of a problem since I haven't supplied a minimal working example.  I will continue to try to construct one that exhibits the problem.

Looking through the code base for `CMAEvolutionStrategy`, I see that the `run!` function evaluates the objective function [here](https://github.com/jbrea/CMAEvolutionStrategy.jl/blob/c9e8a341592f7ff589d8edf41b14972c9ff8340a/src/CMAEvolutionStrategy.jl#L36) via
```
        fvals = evaluate(o.p, f, compute_input(o.p, y))
``` 
The `compute_input` function modifies the inputs using [this code](https://github.com/jbrea/CMAEvolutionStrategy.jl/blob/c9e8a341592f7ff589d8edf41b14972c9ff8340a/src/optimizer.jl#L196-L198):
```
transform!(p.constraints, sigma(p) * y .+ p.mean)
```
I note that the result of `compute_input` does not appear to be saved anywhere.

However, in the `xbest` function, the saved x-value is transformed in [a slightly different way](https://github.com/jbrea/CMAEvolutionStrategy.jl/blob/c9e8a341592f7ff589d8edf41b14972c9ff8340a/src/CMAEvolutionStrategy.jl#L18) before being returned to the caller:
```
xbest(o::Optimizer{<:Any, <:BasicLogger}) = transform(o.p.constraints, o.logger.xbest[end])
```
In this latter transformation for returning `xbest`, there is no multiplication by `sigma(p)` nor addition of `p.mean`.  Could this explain the problem I'm seeing?

Thanks,
Peter

**Comment by jbrea** [comment]
Thank you very much for reporting this issue. This was a sweet little bug (`update!` and `log!` didn't appear in the right order).

**Comment by simonp0420** [comment]
I see I was wrong re the cause of the problem, but thanks very much for the prompt fix!
