### ISSUE TITLE
Does it run in a cluster?

### ISSUE THREAD

**Issue by pjuergens** [jbrea/CMAEvolutionStrategy.jl#4]
Hello :)

I saw that this CMA implementation has a keyword `parallel_evaluation`. I was wondering if it supports running the CMA in a cluster with multiple nodes (using MPI) or if the processes need to be in the same node and it's just using "simple" multiprocessing.

Actually I'm pretty new to parallel computing so I hope the question is understandable ;-)

**Comment by jbrea** [comment]
CMA-ES itself runs always on a single thread (it is computationally very cheap), but in the evaluation of the objective function you can choose whatever parallel computing approach you like. The keyword `parallel_evaluation` affects [how the inputs are passed to the objective function](https://github.com/jbrea/CMAEvolutionStrategy.jl/blob/master/src/optimizer.jl#L199) (see also the description in the docstring `If parallel_evaluation = true, the objective function f receives matrices of n rows (n =
  length(x0)) and popsize columns and should return a vector of length popsize.`). Your objective function could now use MPI (or some other parallel computing approach) to evaluate the different test points of each population (columns of the input matrix) on different nodes and send back the result to the optimizer. This may be sensible if each evaluation of a test point takes a long time to run, such that the overhead of sending the test point to the node and sending the result back is negligible.

**Comment by pjuergens** [comment]
Thanks for the information and the fast reply! That sounds very promosing. It's still some work for me until I can couple my objective function to Julias CMA, but I'll have a deeper look at it then.
