### ISSUE TITLE
Typo in readme NoiseHandler -> NoiseHandling

### ISSUE THREAD

**Issue by Denis-Titov** [jbrea/CMAEvolutionStrategy.jl#5]
In the readme there's a small typo
It says `noise_handling = CMAEvolutionStrategy.NoiseHandler(ασ = 1.1, callback = s -> s > 0)`
But it should be `noise_handling = CMAEvolutionStrategy.NoiseHandling(ασ = 1.1, callback = s -> s > 0)`
It took me a few min to figure out what went wrong so might be useful for other users if this is fixed.
Thanks for the great package!
It improved my optimization time ~10x compared to BlackBoxOptim.jl with no effect on fitness :)

**Comment by jbrea** [comment]
Thanks!
