### ISSUE TITLE
Can I pause and restart the optimization?

### ISSUE THREAD

**Issue by zxjroger** [jbrea/CMAEvolutionStrategy.jl#6]
Hi, thank you for this amazing package. I was wondering if there is a way to pause the optimization and save the progress, then restart it? Thank you.

**Comment by jbrea** [comment]
Sorry, this slipped my attention.

Yes, you can use the internal function `CMAEvolutionStrategy.run!(o, f)`, e.g.
```julia
function rosenbrock(x)
    n = length(x)
    sum(100 * (x[2i-1]^2 - x[2i])^2 + (x[2i-1] - 1)^2 for i in 1:div(n, 2))
end
result = minimize(rosenbrock, zeros(6), 1., maxfevals = 100)
result.stop.maxfevals = 200
CMAEvolutionStrategy.run!(result, rosenbrock)
```
